version: '2'
services:
  nginx:
    image: cmwn/games-nginx:0.1
    container_name: cmwn_games_web
    hostname: "games-local"
    domainname: "changemyworldnow.com"
    ports:
      - "443:443"
    volumes:
      - ./:/var/www/
  node:
    container_name: cmwn_games_node
    build: ./docker/node
    environment:
      DOCKER_HOST_IP: "192.168.99.101"
    volumes:
      - ./:/var/www/
